name: App Development and Migration

on:
  push:
    branches:
      - feature/*
    paths-ignore:
      - 'README.md'
      - 'Contributing.md'

  workflow_dispatch:
    # Manual trigger for any branch
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  development:
    name: Continuous integration of code
    if: github.event_name == 'push' # Only run for push events
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install https://github.com/StrawHatEngineer/CICD_2/releases/download/0.0.7/cicd_aihub-0.0.7-py3-none-any.whl

      - name: Fetch Latest App Data
        run: |
          IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
          SB_NAME=$(jq -r '.source.sb_name' config.json)
          FLOW_PATH=$(jq -r '.source.flow_path' config.json)

          if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
            # Advanced app with file system path
            promote-solution --compile_source_solution --download_solution
          elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
            # Advanced app with Solution Builder
            promote-sb-solution --compile_source_solution --download_solution
          else
            # Regular app without Solution Builder
            promote-build-solution --compile_solution --download_binary
          fi

      - name: Commit app data to feature branch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/*
          COMMIT_MESSAGE=$(jq -r '.release_notes' config.json)
          git add -f .
          git status
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  migrate_to_prod:
    name: Migration to PROD
    if: github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }} 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install https://github.com/StrawHatEngineer/CICD_2/releases/download/0.0.7/cicd_aihub-0.0.7-py3-none-any.whl

      - name: Migrate app to PROD
        run: |
          promote-build-solution --upload_binary --publish_advanced_app --create_deployment
