name: App Development and Migration

on:
  push:
    branches:
      - feature/*
    paths-ignore:
      - 'README.md'
      - 'Contributing.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Contributing.md'

  workflow_dispatch:
    # Manual trigger for any branch
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  development:
    name: Continuous integration of code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install https://github.com/StrawHatEngineer/CICD_2/releases/download/0.0.5/cicd_aihub-0.0.5-py3-none-any.whl

      - name: Fetch Latest App Data
        run: |
          promote-build-solution --compile_solution --download_binary

      - name: Commit app data to feature branch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/*
          COMMIT_MESSAGE=$(jq -r '.release_notes' config.json)
          git add -f .
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  migrate_to_prod:
    name: Migration to PROD
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }} 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install https://github.com/StrawHatEngineer/CICD_2/releases/download/0.0.4/cicd_aihub-0.0.4-py3-none-any.whl

      - name: Migrate app to PROD
        run: |
          promote-build-solution --rebuild
