name: Install Private Python Package

on:
  push:
    branches:
      - main

jobs:
  install-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Download the .whl file
        run: |
          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" -o cicd_aihub-0.0.3-py3-none-any.whl https://github.com/StrawHatEngineer/CICD/releases/download/0.0.3/cicd_aihub-0.0.3-py3-none-any.whl

      - name: Install the package from the .whl file
        run: |
          pip install cicd_aihub-0.0.3-py3-none-any.whl

      - name: Verify installation
        run: |
          python -c "import cicd_aihub; print(cicd_aihub.__version__)"
